version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- ps: nuget pack Result\System1Group.Lib.Result.csproj -Version $env:appveyor_build_version -IncludeReferencedProjects
artifacts:
- path: '*.nupkg'