version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- ps: ls *\**.nuspec | % { nuget.exe pack $_ -Version $env:APPVEYOR_BUILD_VERSION }
artifacts:
- path: '*.nupkg'