version: 2.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
install:
  nuget sources add -name CSharpRuleSet -source https://ci.appveyor.com/nuget/csharpruleset-rxwtqx7d05sl
nuget:
  account_feed: true 
  project_feed: true 
  disable_publish_on_pr: true
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
test_script:
- ps: dotnet test Result.Tests\System1Group.Lib.Result.Tests.csproj
after_build:
- ps: dotnet pack Result\System1Group.Lib.Result.csproj
artifacts:
- path: '**\*.nupkg'